// Generated by ts-to-zod
import { z } from "zod";

export const syncWorkoutDetailsToServerResponseSchema = z.object({
  success: z.boolean(),
  updated: z.array(
    z.object({
      localId: z.number(),
      serverId: z.string(),
      exerciseId: z.number(),
      workoutId: z.string(),
    })
  ),
});
